version: '2'
services:
    wordpress:
        build: ./wordpress
        container_name: ${CONTAINER_NAME_WP}
        restart: always
        links:
            - mariadb:mysql
        expose:
            - 80
        environment:
            - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
            - VIRTUAL_HOST=${URL}
        volumes:
            - ./html:/var/www/html
        networks:
            - nginx-proxy
            - back-end
    mariadb:
        image: mariadb
        container_name: ${CONTAINER_NAME_DB}
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=wordpress
        volumes:
            - ./database:/var/lib/mysql
        networks:
            - back-end
    mail:
        image: tvial/docker-mailserver:2.1
        hostname: mail
        domainname: ${URL}
        container_name: ${CONTAINER_NAME_MAIL}
        ports:
            - "25:25"
            - "143:143"
            - "587:587"
            - "993:993"
        volumes:
            - maildata:/var/mail
            - mailstate:/var/mail-state
            - ./mailconfig/:/tmp/docker-mailserver/
        environment:
            - ENABLE_SPAMASSASSIN=1
            - ENABLE_CLAMAV=1
            - ENABLE_FAIL2BAN=1
            - ENABLE_POSTGREY=1
            - ONE_DIR=1
            - DMS_DEBUG=0
        cap_add:
            - NET_ADMIN
        networks:
            - back-end

volumes:
    maildata:
        driver: local
    mailstate:
        driver: local

networks:
    nginx-proxy:
        external:
            name: nginx-proxy
    back-end:
        driver: bridge
