version: '2'
services:
    wordpress:
        image: dockerhosting/wordpress
        container_name: ${CONTAINER_NAME_WP}
        restart: always
        links:
            - mariadb:mysql
        expose:
            - 80
        environment:
            - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
            - VIRTUAL_HOST=${URL}
            - LETSENCRYPT_HOST=${URL}
            - LETSENCRYPT_EMAIL=${EMAIL}
        volumes:
            - ./html:/var/www/html
        networks:
            - nginx-proxy
            - backend
    mariadb:
        image: dockerhosting/mariadb
        container_name: ${CONTAINER_NAME_DB}
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=wordpress
        volumes:
            - ./database:/var/lib/mysql
        networks:
            - backend
    backup:
        image: dockerhosting/mysql-backup
        restart: always
        container_name: ${CONTAINER_NAME_BACKUP}
        links:
            - mariadb:db
        volumes:
            - ./db_dump:/db
            - ./html:/data
            - ./backup-scripts/rename-and-add-wordpress-html.sh:/scripts.d/post-backup/rename-and-add-wordpress-html.sh
        environment:
            - DB_DUMP_TARGET=/db
            - DB_USER=root
            - DB_PASS=${DB_PASSWORD}
            - DB_DUMP_FREQ=10080
            - DB_DUMP_BEGIN=0100
            - DB_NAMES=wordpress
networks:
    nginx-proxy:
        external:
            name: nginx-proxy
    backend:
        driver: bridge
