version: '2'
services:
    wordpress:
        build: ./wordpress
        container_name: ${CONTAINER_NAME_WP}
        restart: always
        links:
            - mariadb:mysql
        expose:
            - 80
        environment:
            - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
            - VIRTUAL_HOST=${URL}
        volumes:
            - ./html:/var/www/html
        networks:
            - nginx-proxy
            - back-end
    mariadb:
        image: mariadb
        container_name: ${CONTAINER_NAME_DB}
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=wordpress
        volumes:
            - ./database:/var/lib/mysql
        networks:
            - backend
networks:
    nginx-proxy:
        external:
            name: nginx-proxy
    backend:
        driver: bridge
